server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jvlib_db
    username: libuser
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

